name: Move doc/main.pdf to root

on:
  push:
    branches:
      - doc

permissions:
    contents: write

jobs:
    move-pdf-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Move PDF if exists
              run: |
                if [ -f doc/main.pdf ]; then
                mv doc/main.pdf main.pdf
                fi

            - name: Set up Git
              run: |
                git config user.email "actions@github.com"
                git config user.name "GitHub Actions"
                base_branch=$(echo "${GITHUB_REF#refs/heads/}")
                
            - name: Commit and push changes
              run: |
                git add main.pdf
                git commit -m "Move main.pdf to root folder"
                git push origin $base_branch